name: uber_eats
description: A food delivery app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.18
  dio: ^5.0.1
  provider: ^6.0.5
  flutter_svg: ^2.0.2
  intl: ^0.18.0
  pin_code_fields: ^7.4.0
  crypto: ^3.0.2
  encrypt: ^5.0.1
  equatable: ^2.0.5
  uuid: ^3.0.7
  connectivity_plus: ^3.0.3
  path_provider: ^2.0.13
  url_launcher: ^6.1.10
  json_annotation: ^4.8.0
  package_info_plus: ^3.0.3
  device_info_plus: ^8.1.0
  socket_io_client: ^2.0.1
  injectable: ^2.1.0
  get_it: ^7.2.0
  drift: ^2.5.0
  mime_type: ^1.0.0
  mime: ^1.0.2
  sqlite3_flutter_libs: ^0.5.13
  sqflite: ^2.2.4+1
  path: ^1.8.2
  http_parser: ^4.0.2
  flutter_cache_manager: ^3.3.0
  clock: ^1.1.0
  collection: ^1.15.0
  pedantic: ^1.11.1
  rxdart: ">=0.26.0 <0.28.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mockito: ^5.3.2


  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
